[project]
name = "sample-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "mcp[cli]>=1.9.3",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.3",
]
